on consume:
    if {statusEffect::hallucination::%uuid of player%} >= 2:
        chance of 10%:
            cancel event
            play sound "entity.wither.shoot" at player's location
            remove 1 golden apple from player
            send "<#9863e7>Are you sure that's real?" to player

on right click:
    if {statusEffect::hallucination::%uuid of player%} >= 1:
        if player's tool is experience bottle:
            chance of 15%:
                cancel event
                loop 5 times:
                    wait 1 tick
                    remove 1 experience bottle from player
                    drop 1 experience bottle at player's location
        if player's tool is splash potion:
            chance of 15%:
                set {_tool} to player's tool
                cancel event
                loop 5 times:
                    wait 1 tick
                    remove {_tool} from player
                    drop {_tool} at player's location
    if {statusEffect::hallucination::%uuid of player%} >= 2:
        if player's tool or offhand tool is ender pearl:
            player does not have ender pearl on cooldown
            wait a tick
            fake item cooldown of ender pearl for player for 40 ticks
        if player's tool or offhand tool is wind charge:
            player does not have wind charge on cooldown
            wait a tick
            fake item cooldown of wind charge for player for 20 ticks

every 15 seconds:
    loop all players:
        if {statusEffect::hallucination::%loop-player%} >= 1:   
            set {_r} to random integer between 1 and 4
            if {_r} is 1:
                loop 3 times:
                    if {_a} is set:
                        set {_a} to {_a} - 2.5
                        #send "%{_a}%" to loop-player
                    else:
                        set {_a} to loop-player's health * 2 - 2.5
                        #send "%{_a}%" to loop-player

                    wait 0.625 seconds

                    fake loop-player's health to {_a}

                    set {_loc} to loop-player's location
                    add 1 to y-coordinate of {_loc}
                    draw 10 crit particles with offset vector(0.3, 0.5, 0.3) at {_loc} for loop-player

                    play sound "entity.player.attack.crit" with volume 1 and pitch 1 for loop-player

                wait 2.5 seconds

                fake loop-player's health to loop-player's health * 2

command /debug:hallucination <text> [<integer>]:
    permission: op
    trigger:
        if arg-1 is "crit:event":
            loop 3 times:
                if {_a} is set:
                    set {_a} to {_a} - 2.5
                    send "&e&l[DEBUG]&f %{_a}%" to player
                else:
                    set {_a} to player's health * 2 - 2.5
                    send "&e&l[DEBUG]&f %{_a}%" to player

                wait 0.625 seconds

                fake player's health to {_a}

                set {_loc} to player's location
                add 1 to y-coordinate of {_loc}
                draw 10 crit particles with offset vector(0.3, 0.5, 0.3) at {_loc} for player

                play sound "entity.player.attack.crit" with volume 1 and pitch 1 for player

            wait 2.5 seconds

            fake player's health to player's health * 2
        if arg-1 is "sound:event":
            if arg-2 is 1:
                play sound "entity.creeper.primed" to player
                wait 1.85 seconds
                play sound "entity.generic.explode" to player
            if arg-2 is 2:
                play sound "ambient.cave"