import:
    org.bukkit.event.entity.EntityPlaceEvent

on EntityPlaceEvent:
    if event.getEntity() = explosive minecart:
        if event.getPlayer() is in combat:
            cancel event

on chestplate change:
    if event-player is in combat:
        if new armor item is elytra:
            set player's tool to new armor item
            set player's chestplate slot to old armor item 

function noHover() :: itemtype:
    set {_i} to barrier named " "

    hide the entire tooltip of {_i}

    return {_i}

on load:
    register smithing transform recipe:
        id: "minecraft:netherite_chestplate"
        result: diamond chestplate
        template: netherite upgrade smithing template
        base: diamond chestplate
        addition: netherite ingot
    register smithing transform recipe:
        id: "minecraft:netherite_leggings"
        result: diamond leggings
        template: netherite upgrade smithing template
        base: diamond leggings
        addition: netherite ingot
    register smithing transform recipe:
        id: "minecraft:netherite_boots"
        result: diamond boots
        template: netherite upgrade smithing template
        base: diamond boots
        addition: netherite ingot
    register smithing transform recipe:
        id: "minecraft:netherite_helmet"
        result: diamond helmet
        template: netherite upgrade smithing template
        base: diamond helmet
        addition: netherite ingot
    register smithing transform recipe:
        id: "minecraft:netherite_sword"
        result: diamond sword
        template: netherite upgrade smithing template
        base: diamond sword
        addition: netherite ingot
    register smithing transform recipe:
        id: "minecraft:netherite_axe"
        result: diamond axe
        template: netherite upgrade smithing template
        base: diamond axe
        addition: netherite ingot
    register smithing transform recipe:
        id: "minecraft:netherite_pickaxe"
        result: diamond pickaxe
        template: netherite upgrade smithing template
        base: diamond pickaxe
        addition: netherite ingot
    register new shaped recipe:
        id: "minecraft:mace"
        result: noHover()
        shape: " a ", " b "
        category: "combat"
        ingredients:
            set ingredient of "a" to heavy core
            set ingredient of "b" to breeze rod

on craft:
    if event-item is noHover():
        cancel event
        send "&cThis Recipe has been Disabled."

on crafter craft:
    if event-string = "minecraft:mace":
        cancel event
        loop all players in radius 5 of event-location:
            send "&cNice Try." to loop-player

every 5 minute:
    loop all players:
        loop all items in loop-player's inventory:
            if loop-item is enchanted with protection 4:
                enchant loop-item with protection 3
            if loop-item is enchanted with sharpness 5:
                enchant loop-item with sharpness 4
            if loop-item is enchanted with thorns:
                enchant loop-item with thorns 0
            if loop-item is enchanted with fire aspect:
                enchant loop-item with fire aspect 0
            if loop-item is enchanted with density:
                enchant loop-item with density 0
            if loop-item is enchanted with breach 4:
                enchant loop-item with breach 3

on right click:
    if player's tool = splash potion of turtle master or lingering potion of turtle master:
        if player is in combat:
            cancel event
    if player's offhand item = splash potion of turtle master or lingering potion of turtle master:
        if player is in combat:
            cancel event

on uncancelled resurrect attempt:
    if event-entity is in combat:
        if boolean tag "totemUsed" of custom nbt of event-entity is true:
            cancel event
        else:
            set boolean tag "totemUsed" of custom nbt of event-entity to true

on death:
    if boolean tag "totemUsed" of custom nbt of victim is true:
        set boolean tag "totemUsed" of custom nbt of victim to false
        
#every 15 seconds:
 #   loop all players:
  #      if boolean tag "totemUsed" of custom nbt of loop-player is true:
   #         if loop-player is in combat:
    #            stop
     #       else:
      #          set boolean tag "totemUsed" of custom nbt of loop-player to false

on explode:
    event-entity is creeper
    clear exploded blocks

on death:
    if attacker is victim:
        cancel event