using damage sources

function applyKnockback(p: player, e: living entity, YStrength: number, strength: number):
    set {_dir} to vector from yaw {_p}'s yaw and pitch 0
    set {_dir}.y to {_YStrength}  
    set velocity of {_e} to {_dir} * {_strength}

function applyPush(p: player, YStrength: number, strength: number):
    set {_dir} to vector from yaw {_p}'s yaw and pitch 0
    set {_dir}.y to {_YStrength}
    set velocity of {_p} to {_dir} * {_strength}
     
function drawFlash(p: player, isParryable: boolean = false):
    if {_isParryable} is false:
        set {_loc} to location 1 meters infront of {_p}
        add 1 to y-coordinate of {_loc}
        play sound "minecraft:entity.experience_orb.pickup" at {_loc}
        draw 15 dust particle using dustOption(rgb(0, 105, 210), 1) at {_loc}
    else if {_isParryable} is true:
        set {_loc} to location 1 meters infront of {_p}
        add 1 to y-coordinate of {_loc}
        play sound "minecraft:entity.experience_orb.pickup" at {_loc}
        draw 15 dust particle using dustOption(rgb(255, 246, 120), 1) at {_loc}

function drawShapes(loc: location, startRadius: number, endRadius: number, step: number, color1: color, color2: color, speed: number = 4):
    if {_startRadius} > {_endRadius}:
        stop

    set {_current} to {_startRadius}

    while {_current} <= {_endRadius}:
        loop {_speed} times:
            if {_current} > {_endRadius}:
                stop loop

            set {_c1} to a circle of radius {_current}
            set {_c2} to a circle of radius {_current}

            set particle of {_c1} to dust particle using dustOption({_color1}, 1) with force
            set particle of {_c2} to dust particle using dustOption({_color2}, 1) with force

            draw shape {_c1} at {_loc}
            draw shape {_c2} at {_loc}

            add {_step} to {_current}

        wait 1 tick

function applyDamage(p: player, dmg: number, source: damage type, isTrue: boolean = false, pierce: boolean = false):
    if {_isTrue} is true:
        
        set {_armorDamage::helmet} to round({_dmg} * 0.9)
        set {_armorDamage::chestplate} to round({_dmg} * 1.2)
        set {_armorDamage::leggings} to round({_dmg} * 1.1)
        set {_armorDamage::boots} to round({_dmg} * 0.8)

        if helmet of {_p} is not air:
            set {_unbreaking} to unbreaking level of helmet of {_p}

            subtract ({_unbreaking} / 4) from {_armorDamage::helmet}

            if {_armorDamage::helmet} < 0:
                set {_armorDamage::helmet} to 0
            
            if {_pierce} is true:
                damage helmet of {_p} by round({_armorDamage::helmet}) * 6.582
            else:
                damage helmet of {_p} by round({_armorDamage::helmet})

        if chestplate of {_p} is not air:
            set {_unbreaking} to unbreaking level of chestplate of {_p}

            subtract ({_unbreaking} / 4) from {_armorDamage::chestplate}

            if {_armorDamage::chestplate} < 0:
                set {_armorDamage::chestplate} to 0
            
            if {_pierce} is true:
                damage chestplate of {_p} by round({_armorDamage::chestplate}) * 6.582
            else:
                damage chestplate of {_p} by round({_armorDamage::chestplate})

        if leggings of {_p} is not air:
            set {_unbreaking} to unbreaking level of leggings of {_p}

            subtract ({_unbreaking} / 4) from {_armorDamage::leggings}

            if {_armorDamage::leggings} < 0:
                set {_armorDamage::leggings} to 0
            
            if {_pierce} is true:
                damage leggings of {_p} by round({_armorDamage::leggings}) * 6.582
            else:
                damage leggings of {_p} by round({_armorDamage::leggings})

        if boots of {_p} is not air:
            set {_unbreaking} to unbreaking level of boots of {_p}

            subtract ({_unbreaking} / 4) from {_armorDamage::boots}

            if {_armorDamage::boots} < 0:
                set {_armorDamage::boots} to 0

            if {_pierce} is true:
                damage boots of {_p} by round({_armorDamage::boots}) * 6.582
            else:
                damage boots of {_p} by round({_armorDamage::boots})

        set {_heavyArmor} to 0
        
        if {_pierce} is false:
            if helmet of {_p} is diamond helmet or netherite helmet:
                add 1 to {_heavyArmor}
            if chestplate of {_p} is diamond chestplate or netherite chestplate:
                add 1 to {_heavyArmor}
            if leggings of {_p} is diamond leggings or netherite leggings:
                add 1 to {_heavyArmor}
            if boots of {_p} is diamond boots or netherite boots:
                add 1 to {_heavyArmor}

            subtract {_heavyArmor} * 0.25 from {_dmg}

            set {_prot} to 0

            if helmet of {_p} is set:
                add protection level of helmet of {_p} to {_prot}
            if chestplate of {_p} is set:
                add protection level of chestplate of {_p} to {_prot}
            if leggings of {_p} is set:
                add protection level of leggings of {_p} to {_prot}
            if boots of {_p} is set:
                add protection level of boots of {_p} to {_prot}

            set {_reduction} to ({_prot} / 4) - 0.5
            if {_reduction} < 0:
                set {_reduction} to 0
            subtract {_reduction} from {_dmg}
            
        set {_resistance} to amplifier of resistance of {_p}

        if {_resistance} > 0:
            set {_reduction} to {_dmg} * 0.15
            set {_reduction} to {_reduction} * {_resistance}
            subtract {_reduction} from {_dmg}

        if absorption amount of {_p} / 2 > 0:
            if absorption amount of {_p} / 2 >= {_dmg}:
                remove {_dmg} from absorption amount of {_p}
                set {_dmg} to 0
            else:
                subtract absorption amount of {_p} / 2 from {_dmg}
                set absorption amount of {_p} to 0

        if {shatterpointHealth::%{_p}%} is set:
            if {shatterpointHealth::%{_p}%} >= {_dmg}:
                remove {_dmg} from {shatterpointHealth::%{_p}%}
                set {_dmg} to 0
            else:
                remove {shatterpointHealth::%{_p}%} from {_dmg}
                set {shatterpointHealth::%{_p}%} to 0

        if {_dmg} < 0:
            set {_dmg} to 0

        if {_dmg} >= {_p}'s health:
            damage {_p} by {_dmg} * 5 using custom damage source:
                set the damage type to {_source}
            stop

        set {_p}'s health to {_p}'s health - {_dmg}

        wait 1 tick
        damage {_p} by 0.1 using custom damage source:
            set the damage type to {_source}
    else:
        damage {_p} by {_dmg} using custom damage source:
            set the damage type to {_source}

command damagecalculator <number> <integer> [<integer>] [<integer>] [<boolean>]:
    usage: /damagecalculator <damage> <protection> [<resistance>] [<unbreaking level>] [<is diamond/netherite armor>]
    trigger:

        set {_p} to player
        set {_dmg} to arg-1
        send "starter: %{_dmg}%" to {_p}

        set {_prot} to 0
        add arg-2 to {_prot}
        add arg-2 to {_prot}
        add arg-2 to {_prot}
        add arg-2 to {_prot}

        # Protection reduction
        set {_reduction} to ({_prot} / 4) - 0.5
        if {_reduction} < 0:
            set {_reduction} to 0
        subtract {_reduction} from {_dmg}

        send "with prot: %{_dmg}%" to {_p}

        set {_resistance} to arg-3

        if {_resistance} > 0:
            set {_reduction} to {_dmg} * 0.15
            set {_reduction} to {_reduction} * {_resistance}
            subtract {_reduction} from {_dmg}

        if arg-5 is true:
            subtract 1 from {_dmg}
        else:
            send "no heavy (diamond) armor -1" to {_p}

        send "final &o(with resistance if any)&f: %{_dmg}%" to {_p}

        if {_dmg} < 0:
            set {_dmg} to 0

        set {_armorDamage::helmet} to round({_dmg} * 0.9)
        set {_armorDamage::chestplate} to round({_dmg} * 1.2)
        set {_armorDamage::leggings} to round({_dmg} * 1.1)
        set {_armorDamage::boots} to round({_dmg} * 0.8)

        # Helmet
        set {_unbreaking} to arg-4

        subtract ({_unbreaking} / 4) from {_armorDamage::helmet}

        if {_armorDamage::helmet} < 0:
            set {_armorDamage::helmet} to 0

        send "helmet damage: %{_armorDamage::helmet}%" to {_p}

        # Chestplate
        set {_unbreaking} to arg-4

        subtract ({_unbreaking} / 4) from {_armorDamage::chestplate}

        if {_armorDamage::chestplate} < 0:
            set {_armorDamage::chestplate} to 0

        send "chestplate damage: %{_armorDamage::chestplate}%" to {_p}

        # Leggings
        set {_unbreaking} to arg-4

        subtract ({_unbreaking} / 4) from {_armorDamage::leggings}

        if {_armorDamage::leggings} < 0:
            set {_armorDamage::leggings} to 0

        send "legs damage: %{_armorDamage::leggings}%" to {_p}

        # Boots
        set {_unbreaking} to arg-4

        subtract ({_unbreaking} / 4) from {_armorDamage::boots}

        if {_armorDamage::boots} < 0:
            set {_armorDamage::boots} to 0

        send "boots damage: %{_armorDamage::boots}%" to {_p}

command /getitems <text>:
    permission: op
    trigger:
        if arg-1 is "frozen_battleaxe":
            give 2 totem of undying to player
            give 1 diamond axe to player
            give itemWeaponHandle() to player
            give 4 netherite ingots to player
            give 64 ice to player
            give 64 packed ice to player
            give 64 blue ice to player
            give 128 snow block to player

        else if arg-1 is "cloudsplitter":
            give 1 heavy core to player
            give 1 diamond sword to player
            give itemWeaponHandle() to player
            give 4 netherite ingots to player
            give 8 breeze rods to player
            give 48 wind charges to player
            give 24 flow armor trim smithing templates to player

        else if arg-1 is "shadow_dagger":
            give 2 totem of undying to player
            give 1 diamond sword to player
            give itemWeaponHandle() to player
            give 4 netherite ingots to player
            give 64 black dye to player
            give 32 ender pearl to player
            give 16 silence armor trim smithing template to player
            give 16 ward armor trim smithing template to player

        else if arg-1 is "ancient_rune":
            give 2 enchanted golden apple to player
            give 8 echo shard to player
            give 16 flow armor trim smithing template to player
            give 16 tide armor trim smithing template to player
            give 1 trident to player
            give 8 nautilus shell to player
            give 2 heart of the sea to player
            give 32 prismarine shard to player
            give 32 prismarine crystals to player

        else if arg-1 is "reinforced_glove":
            give 64 leather to player
            give 32 iron block to player
            give 4 netherite ingots to player
            give 1 diamond sword to player
            give 16 bolt armor trim smithing template to player
            give itemWeaponHandle() to player
            give 1 heavy core to player
            give 16 silence armor trim smithing template to player

        else if arg-1 is "shard_shooter":
            give 64 amethyst shard to player
            give 32 arrow to player
            give 4 netherite ingots to player
            give 1 crossbow to player
            give 2 totem of undying to player
            give 16 sentry armor trim smithing template to player
            give itemWeaponHandle() to player
            give 16 silence armor trim smithing template to player

on tab complete for "/getitems":
    set tab completions for position 1 to "cloudsplitter", "frozen_battleaxe", "shadow_dagger", "ancient_rune", "reinforced_glove", "shard_shooter"

event "parry":
    pattern: parry
    event-values: player, entity