using damage sources

function itemAncientRune() :: item:
    set {_i} to prismarine crystals of mending 1 named "<#5fe2c5>&lA<#65e5c3>&ln<#6ae7c1>&lc<#70eabe>&li<#76edbc>&le<#7cefba>&ln<#81f2b8>&lt <#8df7b4>&lR<#93fab1>&lu<#98fcaf>&ln<#9effad>&le"

    set {_l::1} to "&8&oA mysterious rune that holds the power of the lakes"
    set {_l::2} to "%nl%<#5fe2c5>ғʟᴏᴡɪɴɢ ᴛɪᴅᴇ"
    set {_l::3} to "&8🕘 -s <#5fe2c5>• ᴘᴀssɪᴠᴇ"
    set {_l::4} to "&7When held in offhand, you get &fWater Breathing&7 and &fDolphin's Grace&7."
    set {_l::5} to "%nl%<#5fe2c5>ʜʏᴅʀᴏsᴄᴀʟɪɴɢ"
    set {_l::6} to "&8🕘 -s <#5fe2c5>• ᴘᴀssɪᴠᴇ"
    set {_l::7} to "&7When you are in rain, you get &fSpeed II&7, &fRegeneration III&7 and &fStrength II&7."
    set {_l::8} to "%nl%<#5fe2c5>ʀɪᴘᴛɪᴅᴇ"
    set {_l::9} to "&8🕘 1m 30s <#5fe2c5>• ʀɪɢʜᴛ-ᴄʟɪᴄᴋ"
    set {_l::10} to "&7You riptide forward, when hitting the ground you damage all entities in a &f5x5&7 radius dealing &f6 ❤&7."
    set {_l::11} to "%nl%<#5fe2c5>ʀɪᴘᴛɪᴅᴇ &7[ALT]"
    set {_l::12} to "&8🕘 1m 45s <#5fe2c5>• ɪɴ ᴏғғʜᴀɴᴅ, sʜɪғᴛ + ʀɪɢʜᴛ-ᴄʟɪᴄᴋ"
    set {_l::13} to "&7You riptide forward, when hitting the ground you damage all entities in a &f10x10&7 radius dealing &f4 ❤&7."

    set boolean tag "ancientRune" of custom nbt of {_i} to true

    set lore of {_i} to {_l::*}

    set item model of {_i} to "minecraft:wild_armor_trim_smithing_template"

    return {_i} with all item flags

on right click:
    if boolean tag "ancientRune" of custom nbt of player's tool is true:
        if {-arun.riptide.CD::%player%} > 0:
            send "<#ff5b5b>Your Riptide is still on cooldown for %{-arun.riptide.CD::%player%}%s" to player
            stop
        drawFlash(player)
        wait 0.5 seconds
        play sound "minecraft:block.beacon.power_select"
        play sound "minecraft:item.trident.riptide_3"
        applyPush(player, 0.15, 6.5)
        wait a tick
        set {-arun_landchck.basic::%player%} to true
        while {-arun_landchck.basic::%player%} is set:
            wait 5 tick
            if player is on ground:
                delete {-arun_landchck.basic::%player%}
                drawFlash(player, true)
                wait 0.15 seconds
                drawShapes(player's location, 0.75, 5, 0.25, rgb(0, 183, 168), rgb(113, 206, 193), 2)
                loop all players in radius 5 of player:
                    if {-isParrying::%loop-player%} is not set:
                        applyDamage(player, 6, drown, true)
                    else:
                        stop loop
    if player is sneaking:
        if boolean tag "ancientRune" of custom nbt of player's offhand tool is true:
            if {-arun.riptide.CD::%player%} > 0:
                send "<#ff5b5b>Your Riptide is still on cooldown for %{-arun.riptide.CD::%player%}%s" to player
                stop
            drawFlash(player)
            wait 0.5 seconds
            play sound "minecraft:block.beacon.power_select"
            play sound "minecraft:item.trident.riptide_3"
            applyPush(player, 0.65, 3.25)
            wait a tick
            set {-arun_landchck.alt::%player%} to true
            while {-arun_landchck.alt::%player%} is set:
                wait 5 tick
                if player is on ground:
                    delete {-arun_landchck.alt::%player%}
                    drawFlash(player, true)
                    wait 0.15 seconds
                    drawShapes(player's location, 0.75, 10, 0.25, rgb(0, 183, 168), rgb(113, 206, 193), 4)
                    loop all players in radius 10 of player:
                        if {-isParrying::%loop-player%} is not set:
                            applyDamage(player, 4, drown, true)
                        else:
                            stop loop