function applyKnockback(p: player, e: living entity, YStrength: number, strength: number):
    set {_dir} to vector from yaw {_p}'s yaw and pitch 0
    set {_dir}.y to {_YStrength}  
    set velocity of {_e} to {_dir} * {_strength}

function applyPush(p: player, YStrength: number, strength: number):
    set {_dir} to vector from yaw {_p}'s yaw and pitch 0
    set {_dir}.y to {_YStrength}
    set velocity of {_p} to {_dir} * {_strength}
     
function drawFlash(p: player, flashType: string = "unparryable"):
    if {_flashType} is "unparryable":
        set {_loc} to location 1 meters infront of {_p}
        add 1 to y-coordinate of {_loc}
        play sound "minecraft:entity.experience_orb.pickup" at {_loc}
        draw 15 dust particle using dustOption(rgb(0, 105, 210), 1) at {_loc}
    else if {_flashType} is "parryable":
        set {_loc} to location 1 meters infront of {_p}
        add 1 to y-coordinate of {_loc}
        play sound "minecraft:entity.experience_orb.pickup" at {_loc}
        draw 15 dust particle using dustOption(rgb(255, 246, 120), 1) at {_loc}