using damage sources

function itemReinforcedGlove() :: item:
    set {_i} to player head of sharpness 5 named "<#ef7272>R<#e86a6a>e<#e26363>i<#db5b5b>n<#d55454>f<#ce4c4c>o<#c84444>r<#c13d3d>c<#bb3535>e<#b42e2e>d <#a71e1e>G<#a11717>l<#9a0f0f>o<#940808>v<#8d0000>e"

    set {_nbt} to "{""minecraft:profile"":{properties:[{name:""textures"",""value"":""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTI2NTU4NWE3OGQwNTYxYWJhNGM5OTQ0NjA5OTdjZDZiYmM4MmM1ODkxOWYzNDEyZGRlZTI0ZDhiZDVkYzdlMCJ9fX0=""}]}}"

    set {_l::1} to "&8&om a k e &f &8&ot h e m &f &8&ob l e e d"
    set {_l::2} to "%nl%<#ef7272>ɴᴀᴛᴜʀᴀʟ sᴛʀᴇɴɢᴛʜ"
    set {_l::3} to "&8🕘 -s <#ef7272>• ᴘᴀssɪᴠᴇ"
    set {_l::4} to "&7The Glove works as a sword."
    set {_l::5} to "%nl%<#ef7272>sᴛʀᴏɴɢ ᴘᴜɴᴄʜ"
    set {_l::6} to "&8🕘 35s <#ef7272>• ᴏғғʜᴀɴᴅ"
    set {_l::7} to "&7You punch forward dealing &f4.5 ❤&7."
    set {_l::8} to "&7Punching whilst being damaged does a &f+PARRY"

    set boolean tag "reinforcedGlove" of custom nbt of {_i} to true

    set lore of {_i} to {_l::*}
    set {_i} to {_i} with nbt compound of {_nbt}

    apply attribute modifier to {_i}:
        attribute: attack damage
        slot: mainhand_slot_group
        id: "minecraft:base_attack_damage"
        amount: 9.0
        operation: add_number

    apply attribute modifier to {_i}:
        attribute: attack speed
        slot: mainhand_slot_group
        id: "minecraft:base_attack_speed"
        amount: -2.8
        operation: add_number

    apply attribute modifier to {_i}:
        attribute: attack knockback
        slot: mainhand_slot_group
        id: "minecraft:base_attack_knockback"
        amount: 1
        operation: add_number

    return {_i} with item flag hide enchants

on death:
    if boolean tag "reinforcedGlove" of custom nbt of attacker's tool is true:
        set death message to "%victim% was beat down by %attacker%'s Reinforced Glove"

on swap item:
    if boolean tag "reinforcedGlove" of custom nbt of player's tool is true:
        if {-rg.pu.CD::%player%} > 0:
            send "<#ff5b5b>Your Strong Punch is still on cooldown for %{-rg.pu.CD::%player%}%s"
            cancel event
            stop
        else:
            cancel event
            #set {-rg.pu.CD::%player%} to 35
            drawFlash(player)
            set {_pla} to event-player's name
            set {-isParrying::%player%} to true
            wait 10 ticks
            if {-isParrying::%player%} is set:
                make player swing their main hand
                applyPush(player, 0, 2.15)
                loop all players in radius 5 of player:
                    if loop-player is not player:
                        set {_source} to a custom damage source:
                            set the damage type to player attack
                            set the causing entity to {_pla}
                            set the direct entity to {_pla}
                        applyDamage(loop-player, 4.5, {_source}, true)
                delete {-isParrying::%player%}

on damage:
    attacker is not victim
    if {-isParrying::%victim%} is set:
        cancel event
        damage attacker by damage + damage
        set {_values::player} to victim

        set {_event} to new custom event "parry" using event-values {_values::*}
        call event {_event}

on parry:
    clear all potion effects of event-player
    make event-player swing their main hand
    set {_loc} to location 0.5 meters infront of event-player
    add 1 to y-coordinate of {_loc}
    play sound "minecraft:item.mace.smash_air" with pitch 1.25 at {_loc}
    draw 5 flash particle using bukkitColor(0,255,255,255) at {_loc}
    heal event-player
    apply saturation 3 to event-player for 1 second
    apply resistance 1 to event-player for 2 minutes
    apply absorption 3 to event-player for 4 minutes
    set invulnerability time of event-player to 15 ticks 
    delete {-isParrying::%event-player%}
    wait a tick
    set tick rate of event-player to 1 and freeze their animations
    wait 6 ticks
    set tick rate of event-player to 20

every second:
    loop all players:
        if {-rg.pu.CD::%loop-player%} is set:
            remove 1 from {-rg.pu.CD::%loop-player%}

on place:
    if event-block is player head:
        cancel event