function itemShardShooter() :: item:
    set {_i} to crossbow of quick charge 4 named "<#f2c6de>S<#f1bad8>h<#f0afd2>a<#efa3cc>r<#ed97c6>d <#eb80ba>S<#ea74b4>h<#e969ae>o<#e85da8>o<#e651a2>t<#e5469c>e<#e43a96>r"

    set {_l::1} to "&8&oi love cooking crystals"
    set {_l::2} to "%nl%<#f2c6de>sʜᴀᴛᴛᴇʀᴘᴏɪɴᴛ"
    set {_l::3} to "&8🕘 40s <#f2c6de>• ᴘᴀssɪᴠᴇ"
    set {_l::4} to "&7Anytime you hit your  you get &f+0.5 <#f2c6de>Shatterpoint&f health.%nl%&7Losing all this health puts it on cooldown."
    set {_l::5} to "%nl%<#f2c6de>ʀᴇsᴏɴᴀᴛᴇ"
    set {_l::6} to "&8🕘 1m 15s <#f2c6de>• ᴏғғʜᴀɴᴅ"
    set {_l::7} to "&7You take a bit to shoot a Resonated Arrow, this arrow will deal &f2x ❤&7."

    set boolean tag "shardShooter" of custom nbt of {_i} to true

    set lore of {_i} to {_l::*}

    return {_i} with item flag hide enchants

on shoot:
    if boolean tag "shardShooter" of custom nbt of shooter's tool is set:
        #{-canResonate::%shooter%} is set
        delete {-canResonate::%shooter%}
        set {-shooter::%event-projectile%} to shooter's uuid

        wait 1 tick
        set {_arrow} to projectile
        set boolean tag "resonatedArrow" of custom nbt of {_arrow} to true

        hide projectile for all entities

on damage:
    projectile is an arrow
    if boolean tag "resonatedArrow" of nbt of projectile is true:
        victim is a player
        
        if {shatterpointHealth::%attacker%} < 10:
            add 0.5 to {shatterpointHealth::%attacker%}
            send "a" to attacker
            
        set damage to damage * 2

on projectile hit:
    projectile is an arrow

    if boolean tag "resonatedArrow" of custom nbt of projectile is true:
        if event-block is set: # Only when it hit a block

            set {_dmg} to 7.5 * 1.5

            loop all players in radius 3 around projectile:
                applyDamage(loop-player, {_dmg}, magic, true)

            play sound "minecraft:block.amethyst_block.break" at location of projectile
            drawShapes(location of projectile, 0.5, 3, 0.15, rgb(232, 120, 255), rgb(188, 120, 255), 2)
        kill projectile

every tick:
    loop all projectiles:
        if boolean tag "resonatedArrow" of custom nbt of loop-projectile is true:
            draw dust particle using dustOption(rgb(228, 107, 246), 1) at loop-projectile

every 5 ticks:
    loop all players:
        if boolean tag "shardShooter" of custom nbt of loop-player's tool is true:
            if {shatterpointHealth::%loop-player%} is not set:
                set {shatterpointHealth::%loop-player%} to 0
            send action bar "&5❤ %{shatterpointHealth::%loop-player%}%" to loop-player