function itemCulLeggings() :: item:
    set {_i} to unbreakable netherite leggings named "<#fcd05c>C<#f5c955>u<#edc14e>l <#dfb33f>L<#d7ab38>e<#d0a431>g<#c89c2a>g<#c19523>i<#ba8e1b>n<#b28614>g<#ab7f0d>s"

    set {_l::1} to "&8&omix their soul with your flame"
    set {_l::2} to "%nl%<#fcd05c>ʙᴜʀɴɪɴɢ ᴘᴀssɪᴏɴ"
    set {_l::3} to "&8🕘 -s <#fcd05c>• ᴘᴀssɪᴠᴇ"
    set {_l::4} to "&7Every 10 critical hits you apply a stack of &fBurning&7 to &fthe victim &7for &f15 seconds%nl%&7Maxes out at &fBurning III"

    set boolean tag "cul_leggings" of custom nbt of {_i} to true

    set armor trim of {_i} to armor trim from copper_material and silence_pattern

    set lore of {_i} to {_l::*}

    return {_i} with item flag hide enchants and hide armor trim

on damage:
    if boolean tag "cul_leggings" of custom nbt of attacker's leggings is true:
        if int tag "cul_leggingsCount" of custom nbt of attacker is 10:
            if {statusEffect::burning::%uuid of victim%} is 3:
                stop
            else:
                set {_a} to {statusEffect::burning::%uuid of victim%} + 1
                console command "statuseffect %victim% Burning %{_a}% 25"
